#!/bin/bash

# Configure how to do screenshots.
time=$(date +%Y-%m-%d-%H-%M-%S)
dir="$(xdg-user-dir)/pictures/screenshots"
file="${time}.png"

# Create the screenshots directory if it doesn't exist.
if [[ ! -d "$dir" ]]; then
  mkdir -p "$dir"
fi

cd ${dir} && grim -g "$(slurp)" - | tee "$file"

exit 0
