#!/bin/bash

SCRIPTS=$HOME/.config/hypr/scripts

# Kill mako and waybar.
_ps=(waybar mako kanshi)

for _prs in "${_ps[@]}"; do
  if [[ $(pidof ${_prs}) ]]; then
    killall -9 ${_prs}
  fi
done

# Re-launch mako and waybar.
${SCRIPTS}/notifications &
${SCRIPTS}/statusbar &
${SCRIPTS}/monitors &
