#!/bin/bash

SCRIPTS=$HOME/.config/hypr/scripts

# kill mako and waybar if they're already running.
_ps=(waybar mako kanshi)

for _prs in "${_ps[@]}"; do
  if [[ $(pidof ${_prs}) ]]; then
    killall -9 ${_prs}
  fi
done

# launch mako, waybar and kanshi.
${SCRIPTS}/notifications &
${SCRIPTS}/statusbar &
${SCRIPTS}/monitors &
