#!/bin/bash

case "$1" in
  "init")
    wal -R
    ;;
  *)
    wal -i "$HOME/pictures/wallpapers/$1.jpg"
    ;;
esac

source "$HOME/.cache/wal/colors.sh"

cp $wallpaper ~/.cache/wallpaper.jpg

_ps=(waybar)

for _prs in "${_ps[@]}"; do
  if [[ $(pidof ${_prs}) ]]; then
    killall -9 ${_prs}
  fi
done

sh "$HOME/.config/hypr/scripts/statusbar" &

pywalfox update

swww img $wallpaper \
    --transition-bezier .43,1.19,1,.4 \
    --transition-fps=60 \
    --transition-type="simple" \
    --transition-duration=0.7 \
    --transition-pos "$( hyprctl cursorpos )"

sleep 1
kanshictl reload
