#!/bin/bash

monitor=(`hyprctl monitors | grep Monitor | awk '{print $2}'`)

case "$1" in
  "init")
    wal -i "$HOME/.cache/wallpaper.jpg"
    ;;
  *)
    wal -i "$HOME/pictures/wallpapers/$1"
    ;;
esac

source "$HOME/.cache/wal/colors.sh"

cp $wallpaper ~/.cache/wallpaper.jpg

_ps=(waybar)

for _prs in "${_ps[@]}"; do
  if [[ $(pidof ${_prs}) ]]; then
    killall -9 ${_prs}
  fi
done

sh "$HOME/.config/hypr/scripts/statusbar" &

pywalfox update

hyprctl hyprpaper unload all
hyprctl hyprpaper preload $wallpaper

for m in ''${monitor[@]}; do
  hyprctl hyprpaper wallpaper "$m,$wallpaper"
done

sleep 1
spicetify update
kanshictl reload
